site_name: Một trang về tự học vẽ
site_description: Một trang tổng hợp rất nhiều thứ liên quan đến vẽ, chỉ đơn giản vậy thôi
site_author: duykhanh471

nav:
  - 'Trang chủ': index.md
  - 'Trước khi bắt đầu':
    - 'FAQ trước khi học vẽ': 'faq-truoc-khi-hoc-ve.md'
    - 'Khởi đầu cho việc học vẽ': 'moi-bat-dau-hoc-ve.md'
  - 'Lộ trình': 'radio-runner.md'
  - 'Tài nguyên': 'tai-nguyen.md'
  - 'Recommendations': 'recs.md'
 

theme:
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.tabs
    - navigation.sections
    - toc.follow
    - search.highlighting
    - search.share
    - search.suggest
  name: material

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - meta
  - admonition
  - attr_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
      
      
plugins:
  - search
  # - open-in-new-tab

extra:
  generator: false
